//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browar.Serwer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PiwoDetailDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PiwoDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowarniaField;
        
        private double PriceField;
        
        private double PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        private double RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Browarnia {
            get {
                return this.BrowarniaField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowarniaField, value) != true)) {
                    this.BrowarniaField = value;
                    this.RaisePropertyChanged("Browarnia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PiwoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PiwoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowarniaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Browarnia {
            get {
                return this.BrowarniaField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowarniaField, value) != true)) {
                    this.BrowarniaField = value;
                    this.RaisePropertyChanged("Browarnia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serwer.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Browar.Serwer.HelloWorldResponse HelloWorld(Browar.Serwer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Browar.Serwer.HelloWorldResponse> HelloWorldAsync(Browar.Serwer.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetBeerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeer", ReplyAction="*")]
        Browar.Serwer.GetBeerResponse GetBeer(Browar.Serwer.GetBeerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeer", ReplyAction="*")]
        System.Threading.Tasks.Task<Browar.Serwer.GetBeerResponse> GetBeerAsync(Browar.Serwer.GetBeerRequest request);
        
        // CODEGEN: Generating message contract since element name GetBeersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        Browar.Serwer.GetBeersResponse GetBeers(Browar.Serwer.GetBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBeers", ReplyAction="*")]
        System.Threading.Tasks.Task<Browar.Serwer.GetBeersResponse> GetBeersAsync(Browar.Serwer.GetBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePiwo", ReplyAction="*")]
        bool DeletePiwo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePiwo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeletePiwoAsync(int id);
        
        // CODEGEN: Generating message contract since element name piwo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiwo", ReplyAction="*")]
        Browar.Serwer.UpdatePiwoResponse UpdatePiwo(Browar.Serwer.UpdatePiwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePiwo", ReplyAction="*")]
        System.Threading.Tasks.Task<Browar.Serwer.UpdatePiwoResponse> UpdatePiwoAsync(Browar.Serwer.UpdatePiwoRequest request);
        
        // CODEGEN: Generating message contract since element name piwo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPiwo", ReplyAction="*")]
        Browar.Serwer.InsertPiwoResponse InsertPiwo(Browar.Serwer.InsertPiwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPiwo", ReplyAction="*")]
        System.Threading.Tasks.Task<Browar.Serwer.InsertPiwoResponse> InsertPiwoAsync(Browar.Serwer.InsertPiwoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PoliczOcene", ReplyAction="*")]
        double PoliczOcene(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PoliczOcene", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PoliczOceneAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Browar.Serwer.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Browar.Serwer.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeer", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.GetBeerRequestBody Body;
        
        public GetBeerRequest() {
        }
        
        public GetBeerRequest(Browar.Serwer.GetBeerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetBeerRequestBody() {
        }
        
        public GetBeerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.GetBeerResponseBody Body;
        
        public GetBeerResponse() {
        }
        
        public GetBeerResponse(Browar.Serwer.GetBeerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Browar.Serwer.PiwoDetailDTO GetBeerResult;
        
        public GetBeerResponseBody() {
        }
        
        public GetBeerResponseBody(Browar.Serwer.PiwoDetailDTO GetBeerResult) {
            this.GetBeerResult = GetBeerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeers", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.GetBeersRequestBody Body;
        
        public GetBeersRequest() {
        }
        
        public GetBeersRequest(Browar.Serwer.GetBeersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBeersRequestBody {
        
        public GetBeersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBeersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBeersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.GetBeersResponseBody Body;
        
        public GetBeersResponse() {
        }
        
        public GetBeersResponse(Browar.Serwer.GetBeersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBeersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Browar.Serwer.PiwoDTO[] GetBeersResult;
        
        public GetBeersResponseBody() {
        }
        
        public GetBeersResponseBody(Browar.Serwer.PiwoDTO[] GetBeersResult) {
            this.GetBeersResult = GetBeersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiwo", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.UpdatePiwoRequestBody Body;
        
        public UpdatePiwoRequest() {
        }
        
        public UpdatePiwoRequest(Browar.Serwer.UpdatePiwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiwoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Browar.Serwer.PiwoDetailDTO piwo;
        
        public UpdatePiwoRequestBody() {
        }
        
        public UpdatePiwoRequestBody(Browar.Serwer.PiwoDetailDTO piwo) {
            this.piwo = piwo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePiwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePiwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.UpdatePiwoResponseBody Body;
        
        public UpdatePiwoResponse() {
        }
        
        public UpdatePiwoResponse(Browar.Serwer.UpdatePiwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePiwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdatePiwoResult;
        
        public UpdatePiwoResponseBody() {
        }
        
        public UpdatePiwoResponseBody(bool UpdatePiwoResult) {
            this.UpdatePiwoResult = UpdatePiwoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPiwoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPiwo", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.InsertPiwoRequestBody Body;
        
        public InsertPiwoRequest() {
        }
        
        public InsertPiwoRequest(Browar.Serwer.InsertPiwoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPiwoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Browar.Serwer.PiwoDetailDTO piwo;
        
        public InsertPiwoRequestBody() {
        }
        
        public InsertPiwoRequestBody(Browar.Serwer.PiwoDetailDTO piwo) {
            this.piwo = piwo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPiwoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPiwoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Browar.Serwer.InsertPiwoResponseBody Body;
        
        public InsertPiwoResponse() {
        }
        
        public InsertPiwoResponse(Browar.Serwer.InsertPiwoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPiwoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertPiwoResult;
        
        public InsertPiwoResponseBody() {
        }
        
        public InsertPiwoResponseBody(bool InsertPiwoResult) {
            this.InsertPiwoResult = InsertPiwoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Browar.Serwer.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Browar.Serwer.ServiceSoap>, Browar.Serwer.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Browar.Serwer.HelloWorldResponse Browar.Serwer.ServiceSoap.HelloWorld(Browar.Serwer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Browar.Serwer.HelloWorldRequest inValue = new Browar.Serwer.HelloWorldRequest();
            inValue.Body = new Browar.Serwer.HelloWorldRequestBody();
            Browar.Serwer.HelloWorldResponse retVal = ((Browar.Serwer.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Browar.Serwer.HelloWorldResponse> Browar.Serwer.ServiceSoap.HelloWorldAsync(Browar.Serwer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Browar.Serwer.HelloWorldResponse> HelloWorldAsync() {
            Browar.Serwer.HelloWorldRequest inValue = new Browar.Serwer.HelloWorldRequest();
            inValue.Body = new Browar.Serwer.HelloWorldRequestBody();
            return ((Browar.Serwer.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Browar.Serwer.GetBeerResponse Browar.Serwer.ServiceSoap.GetBeer(Browar.Serwer.GetBeerRequest request) {
            return base.Channel.GetBeer(request);
        }
        
        public Browar.Serwer.PiwoDetailDTO GetBeer(int id) {
            Browar.Serwer.GetBeerRequest inValue = new Browar.Serwer.GetBeerRequest();
            inValue.Body = new Browar.Serwer.GetBeerRequestBody();
            inValue.Body.id = id;
            Browar.Serwer.GetBeerResponse retVal = ((Browar.Serwer.ServiceSoap)(this)).GetBeer(inValue);
            return retVal.Body.GetBeerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Browar.Serwer.GetBeerResponse> Browar.Serwer.ServiceSoap.GetBeerAsync(Browar.Serwer.GetBeerRequest request) {
            return base.Channel.GetBeerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Browar.Serwer.GetBeerResponse> GetBeerAsync(int id) {
            Browar.Serwer.GetBeerRequest inValue = new Browar.Serwer.GetBeerRequest();
            inValue.Body = new Browar.Serwer.GetBeerRequestBody();
            inValue.Body.id = id;
            return ((Browar.Serwer.ServiceSoap)(this)).GetBeerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Browar.Serwer.GetBeersResponse Browar.Serwer.ServiceSoap.GetBeers(Browar.Serwer.GetBeersRequest request) {
            return base.Channel.GetBeers(request);
        }
        
        public Browar.Serwer.PiwoDTO[] GetBeers() {
            Browar.Serwer.GetBeersRequest inValue = new Browar.Serwer.GetBeersRequest();
            inValue.Body = new Browar.Serwer.GetBeersRequestBody();
            Browar.Serwer.GetBeersResponse retVal = ((Browar.Serwer.ServiceSoap)(this)).GetBeers(inValue);
            return retVal.Body.GetBeersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Browar.Serwer.GetBeersResponse> Browar.Serwer.ServiceSoap.GetBeersAsync(Browar.Serwer.GetBeersRequest request) {
            return base.Channel.GetBeersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Browar.Serwer.GetBeersResponse> GetBeersAsync() {
            Browar.Serwer.GetBeersRequest inValue = new Browar.Serwer.GetBeersRequest();
            inValue.Body = new Browar.Serwer.GetBeersRequestBody();
            return ((Browar.Serwer.ServiceSoap)(this)).GetBeersAsync(inValue);
        }
        
        public bool DeletePiwo(int id) {
            return base.Channel.DeletePiwo(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePiwoAsync(int id) {
            return base.Channel.DeletePiwoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Browar.Serwer.UpdatePiwoResponse Browar.Serwer.ServiceSoap.UpdatePiwo(Browar.Serwer.UpdatePiwoRequest request) {
            return base.Channel.UpdatePiwo(request);
        }
        
        public bool UpdatePiwo(Browar.Serwer.PiwoDetailDTO piwo) {
            Browar.Serwer.UpdatePiwoRequest inValue = new Browar.Serwer.UpdatePiwoRequest();
            inValue.Body = new Browar.Serwer.UpdatePiwoRequestBody();
            inValue.Body.piwo = piwo;
            Browar.Serwer.UpdatePiwoResponse retVal = ((Browar.Serwer.ServiceSoap)(this)).UpdatePiwo(inValue);
            return retVal.Body.UpdatePiwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Browar.Serwer.UpdatePiwoResponse> Browar.Serwer.ServiceSoap.UpdatePiwoAsync(Browar.Serwer.UpdatePiwoRequest request) {
            return base.Channel.UpdatePiwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Browar.Serwer.UpdatePiwoResponse> UpdatePiwoAsync(Browar.Serwer.PiwoDetailDTO piwo) {
            Browar.Serwer.UpdatePiwoRequest inValue = new Browar.Serwer.UpdatePiwoRequest();
            inValue.Body = new Browar.Serwer.UpdatePiwoRequestBody();
            inValue.Body.piwo = piwo;
            return ((Browar.Serwer.ServiceSoap)(this)).UpdatePiwoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Browar.Serwer.InsertPiwoResponse Browar.Serwer.ServiceSoap.InsertPiwo(Browar.Serwer.InsertPiwoRequest request) {
            return base.Channel.InsertPiwo(request);
        }
        
        public bool InsertPiwo(Browar.Serwer.PiwoDetailDTO piwo) {
            Browar.Serwer.InsertPiwoRequest inValue = new Browar.Serwer.InsertPiwoRequest();
            inValue.Body = new Browar.Serwer.InsertPiwoRequestBody();
            inValue.Body.piwo = piwo;
            Browar.Serwer.InsertPiwoResponse retVal = ((Browar.Serwer.ServiceSoap)(this)).InsertPiwo(inValue);
            return retVal.Body.InsertPiwoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Browar.Serwer.InsertPiwoResponse> Browar.Serwer.ServiceSoap.InsertPiwoAsync(Browar.Serwer.InsertPiwoRequest request) {
            return base.Channel.InsertPiwoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Browar.Serwer.InsertPiwoResponse> InsertPiwoAsync(Browar.Serwer.PiwoDetailDTO piwo) {
            Browar.Serwer.InsertPiwoRequest inValue = new Browar.Serwer.InsertPiwoRequest();
            inValue.Body = new Browar.Serwer.InsertPiwoRequestBody();
            inValue.Body.piwo = piwo;
            return ((Browar.Serwer.ServiceSoap)(this)).InsertPiwoAsync(inValue);
        }
        
        public double PoliczOcene(int id) {
            return base.Channel.PoliczOcene(id);
        }
        
        public System.Threading.Tasks.Task<double> PoliczOceneAsync(int id) {
            return base.Channel.PoliczOceneAsync(id);
        }
    }
}
